 /*
 h2 접속 쉘명령어
 cd Downloads/h2/bin
 ./h2.sh


 */

 drop table if exists member CASCADE;
 create table member
 (
   id   bigint generated by default as identity,
   name varchar(255),
   primary key (id)
);

